'use strict'
Object.defineProperty(exports, '__esModule', { value: true })
const vue_1 = require('vue')
require('./registerServiceWorker')
const App_vue_1 = require('./App.vue')
const router_1 = require('./router')
const store_1 = require('./store')
require('./main.scss')
// import './assets/tailwind.css'
const Md2Button_vue_1 = require('../md2/Button/Md2Button.vue')
const Md2Image_vue_1 = require('../md2/Image/Md2Image.vue')
const Md2Icon_vue_1 = require('../md2/Icon/Md2Icon.vue')
const vueItem = (0, vue_1.createApp)(App_vue_1.default)
  .use(store_1.default)
  .use(router_1.default)
vueItem.component('md2-button', Md2Button_vue_1.default)
vueItem.component('md2-image', Md2Image_vue_1.default)
vueItem.component('md2-icon', Md2Icon_vue_1.default)
vueItem.mount('#app-test')
// # sourceMappingURL=main.js.map
